"""Convert a binary file to a C++ byte array."""
import sys
from pathlib import Path


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("usage: bin_to_cpp.py <input.bin> <output.cpp> <symbol_prefix>")
    src = Path(sys.argv[1]).read_bytes()
    out = Path(sys.argv[2])
    sym = sys.argv[3]
    lines = [
        "// Auto-generated by bin_to_cpp.py",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        f"alignas(8) std::uint8_t {sym}Data[] = {{",
    ]
    for i in range(0, len(src), 16):
        chunk = src[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += [
        "};",
        f"std::size_t {sym}Size = sizeof({sym}Data);",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(src)} bytes)")


if __name__ == "__main__":
    main()
