# Generate embedded_data.rc + manifest for loc/*.json and assets/** (Release uses MAKU_EMBED_DATA).

function(maku_collect_embed_files out_var)
    set(_files "")
    file(GLOB _loc CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/loc/*.json")
    foreach(_path IN LISTS _loc)
        get_filename_component(_name "${_path}" NAME)
        # Only two-letter locale tags (en.json, ru.json) — skip caches and helper JSON.
        if(_name MATCHES "^[a-z][a-z]\\.json$")
            list(APPEND _files "${_path}")
        endif()
    endforeach()
    file(GLOB_RECURSE _assets CONFIGURE_DEPENDS
        "${CMAKE_SOURCE_DIR}/assets/fonts/*"
        "${CMAKE_SOURCE_DIR}/assets/icons/*"
        "${CMAKE_SOURCE_DIR}/assets/images/*")
    list(APPEND _files ${_assets})
    set(${out_var} "${_files}" PARENT_SCOPE)
endfunction()

function(maku_generate_embedded_data)
    maku_collect_embed_files(_embed_files)
    set(_out_dir "${CMAKE_BINARY_DIR}/embed")
    file(MAKE_DIRECTORY "${_out_dir}")

    set(_id 3000)
    set(_rc "")
    set(_manifest "/* Auto-generated by cmake/EmbedData.cmake — do not edit. */\n")
    string(APPEND _manifest "#include \"core/EmbeddedData.h\"\n\n")
    string(APPEND _manifest "namespace maku::embed::detail {\n\n")
    string(APPEND _manifest "const Entry kEntries[] = {\n")

    foreach(_abs IN LISTS _embed_files)
        if(NOT EXISTS "${_abs}")
            continue()
        endif()
        file(RELATIVE_PATH _rel "${CMAKE_SOURCE_DIR}" "${_abs}")
        string(REPLACE "\\" "/" _rel "${_rel}")

        file(TO_CMAKE_PATH "${_abs}" _rc_path)
        string(APPEND _rc "${_id} RCDATA \"${_rc_path}\"\n")
        string(APPEND _manifest "    {\"${_rel}\", ${_id}},\n")
        math(EXPR _id "${_id} + 1")
    endforeach()

    string(APPEND _manifest "};\n\n")
    string(APPEND _manifest
           "const std::size_t kEntryCount = sizeof(kEntries) / sizeof(kEntries[0]);\n")
    string(APPEND _manifest "} // namespace maku::embed::detail\n")

    file(WRITE "${_out_dir}/embedded_data.rc" "${_rc}")
    file(WRITE "${_out_dir}/embedded_manifest.cpp" "${_manifest}")

    set(MAKU_EMBED_RC "${_out_dir}/embedded_data.rc" PARENT_SCOPE)
    set(MAKU_EMBED_MANIFEST "${_out_dir}/embedded_manifest.cpp" PARENT_SCOPE)
    set(MAKU_EMBED_DEPENDS "${_embed_files}" PARENT_SCOPE)
endfunction()

function(maku_setup_embedded_data target)
    maku_generate_embedded_data()

    target_sources(${target} PRIVATE
        "${CMAKE_SOURCE_DIR}/src/core/EmbeddedData.cpp"
        $<$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>:${MAKU_EMBED_RC}>
        $<$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>:${MAKU_EMBED_MANIFEST}>
    )
    if(MAKU_EMBED_DEPENDS)
        set_source_files_properties("${MAKU_EMBED_RC}" PROPERTIES OBJECT_DEPENDS "${MAKU_EMBED_DEPENDS}")
    endif()

    target_compile_definitions(${target} PRIVATE
        $<$<OR:$<CONFIG:Release>,$<CONFIG:MinSizeRel>>:MAKU_EMBED_DATA=1>
    )
endfunction()
